// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1750799211);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1750799191);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1750799186);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1750799241);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 6732);
user_pref("browser.cache.disk.capacity", 880640);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1750799182);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4be54e54-ce77-45dd-9c42-13a55ffbc94c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1750799252128");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1750801052128");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1750799192333");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1750820792333");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1750799190");
user_pref("browser.slowStartup.averageTime", 3974);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1750799184);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1750799189189");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "2215fa35cdfc4d47bb14d68c0dad9944");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3d12620d-701d-4f02-bb09-468a0bcb5a96\",\"formautofill@mozilla.org\":\"b12d01fb-38c3-404b-be86-e8627c953084\",\"screenshots@mozilla.org\":\"bbb5c197-f239-4b83-9b9e-4b148f6e719d\",\"webcompat-reporter@mozilla.org\":\"8cb941df-7909-4f36-882a-82f712f2dbb2\",\"webcompat@mozilla.org\":\"4b5ddcce-b056-4871-8658-e29b84b8f5af\",\"default-theme@mozilla.org\":\"822a3bf3-8637-4e98-829f-51213e77ef79\",\"google@search.mozilla.org\":\"6126a8b2-8b55-4c77-88ab-4a552ebd4895\",\"amazondotcom@search.mozilla.org\":\"685263e0-85b3-42aa-a7ca-b88e06657c5c\",\"bing@search.mozilla.org\":\"f42f7700-c981-4638-ae51-51c876909746\",\"ddg@search.mozilla.org\":\"1c0a2197-4589-4f58-b698-b23a7369e4bb\",\"ebay@search.mozilla.org\":\"05bff639-a9b4-449b-b3ed-b09f94c5e191\",\"twitter@search.mozilla.org\":\"7090affa-0df2-4325-a4a1-b1ed72d38af9\",\"wikipedia@search.mozilla.org\":\"d3bf698a-ed21-46dc-99ad-c6faaf9eb1f9\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "9096f995-9fc6-40cb-a306-62dde8a83b4f");
user_pref("security.sandbox.plugin.tempDirSuffix", "6987d9ed-43b1-4a1a-9a4d-9e222610c0f4");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1750799180);
user_pref("toolkit.telemetry.cachedClientID", "10465906-c43b-44e9-bc9d-b1f6b276541e");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
